import { Project, WilmaColor } from './types';

export const WILMA_COLORS = {
  yellow: WilmaColor.Yellow,
  darkNavy: WilmaColor.DarkNavy,
  lightBlue: WilmaColor.LightBlue,
  mediumBlue: WilmaColor.MediumBlue,
  grey: WilmaColor.Grey,
  pink: WilmaColor.Pink,
};

export const PROJECTS: Project[] = [
  // Baden-Württemberg
  {
    id: 'ensemble-hoefe',
    city: 'Salach',
    name: 'Ensemble Höfe',
    region: 'Baden-Württemberg',
    description: 'Dann sind Sie in den Ensemble Höfen am Ziel Ihrer Wünsche angekommen – ganz gleich, ob es um Wohnkomfort oder Nachhaltigkeit geht.',
    link: "https://www.wilma.de/projekte/baden-wuerttemberg/salach-ensemble-hoefe.html",
  },
  {
    id: 'korber-viertele',
    city: 'Korb',
    name: 'Korber Viertele',
    region: 'Baden-Württemberg',
    description: 'Ein Baukonzept, das den Bedürfnissen der Bewohner optimal gerecht wird, Wohlfühlräume schafft, perfekt mit seiner Umgebung harmoniert und hohe Energieeffizienz sicherstellt.',
    link: "https://www.wilma.de/projekte/baden-wuerttemberg/korb-korber-viertele.html",
  },
  {
    id: 'sunny',
    city: 'Schwäbisch Hall',
    name: 'sunny',
    region: 'Baden-Württemberg',
    description: 'Stadtnah statt weit weg. „sunny – Wohnen am Sonnenrain" steht für beste Wohnqualität im neuen Wohngebiet „Sonnenrain".',
    link: "https://www.wilma.de/projekte/baden-wuerttemberg/schwaebisch-hall-sunny.html",
  },

  // Bayern
  {
    id: 'hublandview',
    city: 'Würzburg',
    name: 'HublandView',
    region: 'Bayern',
    description: 'Hier entstehen in absoluter Bestlage 24 Townhäuser nach modernsten Standards zu attraktiven Konditionen.',
    link: "https://www.wilma.de/projekte/bayern/wuerzburg-hublandview.html",
  },
  {
    id: 'marienplatz',
    city: 'Tutzing',
    name: 'Marienplatz',
    region: 'Bayern',
    description: 'An einem dieser Orte – in Tutzing am Ufer des Starnberger Sees – könnten Sie schon bald Ihr neues Zuhause haben.',
    link: "https://www.wilma.de/projekte/bayern/tutzing.html",
  },
  {
    id: 'seilerbruecklwiesen',
    city: 'Freising',
    name: 'Seilerbrücklwiesen',
    region: 'Bayern',
    description: 'Ihr neues Zuhause in Freising. Idyllische Isarauen, ein romantischer Wald und dann – direkt daneben – Ihr liebevoll gestaltetes neues Eigenheim.',
    link: "https://www.wilma.de/projekte/bayern/freising.html",
  },
  {
    id: 'hubland-nord',
    city: 'Würzburg',
    name: 'Würzburg, Hubland Nord',
    region: 'Bayern',
    description: 'Einfamilienhäuser und Eigentumswohnungen im Quartier Hubland-Nord.',
    link: "https://www.wilma.de/projekte/bayern/wuerzburg-hubland-quartier-vormerken.html",
  },

  // Hessen
  {
    id: 'artem',
    city: 'Oberursel',
    name: 'Artem',
    region: 'Hessen',
    description: 'Sie lieben es, zentral zu wohnen? Dann sind Sie hier genau richtig! Mitten in Oberursel entwickeln wir für Sie im neuen Stadtquartier „Artem" Eigentumswohnungen für alle Ansprüche.',
    link: "https://www.wilma.de/projekte/hessen/oberursel-artem.html",
  },
  {
    id: 'feel-good-pioneer-park',
    city: 'Hanau',
    name: 'Feel good im Pioneer Park',
    region: 'Hessen',
    description: 'Hanaus großes Konversionsprojekt setzt ein Ausrufezeichen. Aus dem Gelände der ehemaligen Pioneer Kaserne ist Zug um Zug ein lebendiges Wohnquartier geworden.',
    link: "https://www.wilma.de/projekte/hessen/hanau-feel-good-im-pioneer-park.html",
  },
  {
    id: 'qurs',
    city: 'Bad Vilbel',
    name: 'QURS',
    region: 'Hessen',
    description: 'Mit gehobener Ausstattung, modernster Energietechnik und einer zentralen Lage ist das QURS-Quellenquartier der perfekte Ort zum Leben und Investieren.',
    link: "https://www.wilma.de/projekte/hessen/bad-vilbel-qurs.html",
  },
  {
    id: 'schoeffergaerten',
    city: 'Gernsheim',
    name: 'Schöffergärten',
    region: 'Hessen',
    description: 'Auf dem 17.730 m² großen Areal am Ortsrand von Gernsheim, im Neubaugebiet „Östlich der Ringstraße" realisiert WILMA in 4 Bauabschnitten Einfamilienhäuser.',
    link: "https://www.wilma.de/projekte/hessen/gernsheim-schoeffergaerten.html",
  },
  {
    id: 'urban-east',
    city: 'Offenbach am Main',
    name: 'URBAN EAST',
    region: 'Hessen',
    description: 'Herzstück im neuen Quartier 4.0, auf dem ehemaligen Güterbahnhofsgelände Offenbach. Optimaler Mix: 90 % Wohnungen, 10 % Gewerbe.',
    link: "https://www.wilma.de/projekte/hessen/offenbach-am-main-urban-east.html",
  },

  // Nordrhein-Westfalen
  {
    id: '4-viertel',
    city: 'Essen',
    name: '4/Viertel',
    region: 'Nordrhein-Westfalen',
    description: 'Das Bauvorhaben sieht ein Karree aus vier ansprechenden Mehrfamilienhäusern mit insgesamt 60 Wohnungen vor. Die Lage ist perfekt zwischen dem weitläufigen Hallo-Park und dem Weltkulturerbe Zollverein gelegen.',
    link: "https://www.wilma.de/projekte/nordrhein-westfalen/essen-stoppenberg-hallostrasse.html",
  },
  {
    id: 'am-auenpark',
    city: 'Selm',
    name: 'Am Auenpark',
    region: 'Nordrhein-Westfalen',
    description: 'Wohneigentum am Auenpark ist für Menschen, die das Angenehme mit dem Nützlichen verbinden. Für Wohngenießer, die dabei auch an die Zukunft denken.',
    link: "https://www.wilma.de/projekte/nordrhein-westfalen/selm-am-auenpark.html",
  },
  {
    id: 'am-rauhen-holz',
    city: 'Dortmund',
    name: 'AM RAUHEN HOLZ',
    region: 'Nordrhein-Westfalen',
    description: 'Hier lebt man heute und in Zukunft natur- und stadtnah, perfekt angebunden und integriert in eine erstklassige Infrastruktur.',
    link: "https://www.wilma.de/projekte/nordrhein-westfalen/dortmund-luetgendortmund-karinstrasse.html",
  },
  {
    id: 'doverener-muehle',
    city: 'Hückelhoven',
    name: 'Doverener Mühle',
    region: 'Nordrhein-Westfalen',
    description: 'Lassen Sie sich von den ansprechenden Doppelhaushälften oder modernen Reihenhäusern mit viel Freiraum für alle Generationen dank sonniger Terrassen und eigenem Garten überzeugen.',
    link: "https://www.wilma.de/projekte/nordrhein-westfalen/hueckelhoven-doverener-muehle.html",
  },
  {
    id: 'frohnhofsquartier',
    city: 'Düren',
    name: 'FROHNHOFSQUARTIER',
    region: 'Nordrhein-Westfalen',
    description: 'Sie bieten insgesamt 20 attraktive 2- bis 4-Zimmer-Wohnungen mit klug geplanten Grundrissen. Sämtliche Wohnungen verfügen ebenfalls über Freiraum für die Bewohner.',
    link: "https://www.wilma.de/projekte/nordrhein-westfalen/dueren-arnoldsweiler-frohnhofsquartier.html",
  },
  {
    id: 'homeberg',
    city: 'Duisburg',
    name: 'HOMeBERG',
    region: 'Nordrhein-Westfalen',
    description: 'Im grünen Vorort Alt-Homberg vereinen sich scheinbare Gegensätze: Hier ist man natur- und stadtnah, perfekt angebunden und integriert in eine erstklassige Infrastruktur.',
    link: "https://www.wilma.de/projekte/nordrhein-westfalen/duisburg-homeberg.html",
  },
  {
    id: 'impuls',
    city: 'Düsseldorf',
    name: 'IMPULS',
    region: 'Nordrhein-Westfalen',
    description: 'Hier wird nicht nur neuer Wohnraum geschaffen, sondern auch ein Raum für Gemeinschaftsleben, in dem Nachbarschaft und Zusammenhalt im neuen Quartier ihren Platz finden.',
    link: "https://www.wilma.de/projekte/nordrhein-westfalen/duesseldorf-impuls.html",
  },
  {
    id: 'lebenswert-lank',
    city: 'Meerbusch',
    name: 'LEBENSWERT LANK',
    region: 'Nordrhein-Westfalen',
    description: 'Willkommen in Meerbusch-Lank – wo Wohnen zum Wohlfühlen wird. Ob moderne Wohnung oder großzügiges Haus – im LEBENSWERT LANK finden Sie Ihr neues Zuhause.',
    link: "https://www.wilma.de/projekte/nordrhein-westfalen/living-lank-meerbusch.html",
  },
  {
    id: 'max-und-mauritz',
    city: 'Krefeld',
    name: 'MAX + MAURITZ',
    region: 'Nordrhein-Westfalen',
    description: 'Geplant sind 74 Wohnungen und 124 Häuser.',
    link: "https://www.wilma.de/projekte.html",
  },
  {
    id: 'quartier-glueckstrasse',
    city: 'Dortmund-Derne',
    name: 'Quartier Glückstraße',
    region: 'Nordrhein-Westfalen',
    description: 'Geplant ist die Schaffung eines attraktiven neuen Wohnquartiers, welches durch eine grüne Quartiersmitte geprägt ist.',
    link: "https://www.wilma.de/projekte/nordrhein-westfalen/glueck-auf-quartier-dortmund-derne.html",
  },
  {
    id: 'weinberger-gaerten',
    city: 'Meckenheim',
    name: 'WEINBERGER GÄRTEN',
    region: 'Nordrhein-Westfalen',
    description: 'An der Gudenauer Allee in Meckenheim entsteht das neue Wohnquartier WEINBERGER GÄRTEN mit insgesamt 83 Einfamilienhäusern.',
    link: "https://www.wilma.de/projekte/nordrhein-westfalen/meckenheim-weinberger-gaerten.html",
  },

  // Rheinland-Pfalz
  {
    id: 'rebstock-quartier',
    city: 'Bad Kreuznach',
    name: 'Rebstock Quartier',
    region: 'Rheinland-Pfalz',
    description: 'Erleben Sie das Rebstock Quartier in Bad Kreuznach: Ein urbanes Wohnprojekt, das modernen Komfort mit naturnaher Umgebung verbindet.',
    link: "https://www.wilma.de/projekte/rheinland-pfalz/bad-kreuznach-rebstock-quartier.html",
  },
];